# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KartverketAdresse
                                 A QGIS plugin
 This plugin fetches coordinates for Norwegian addresses using the Kartverket open adress-API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-28
        copyright            : (C) 2022 by Morten Sickel
        email                : morten@sickel.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KartverketAdresse class from file KartverketAdresse.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .kartverket_adresse import KartverketAdresse
    return KartverketAdresse(iface)
